### PR TITLE
Try to locate the user's SDK path when none provided

### LINKED ISSUE #60: automatically locate the SDK
This would be nice to have. Many people installing `dart-tools` will already have an SDK installed. It'll mean they have one fewer setup steps to do dart development.

Here's a technique I've used for other tooling. locating the VM:
- on a mac, run `/bin/bash -l -c "which dart"`. You want to run it in bash since exec runs in csh (I think?), but most people have their env vars set up in bash
- linux, `which dart`
- windows, `where dart.exe` (and possibly fall back to parsing the PATH var)

Once you have the vm, you want to find the sdk. Tools like brew install the vm in a symlinked dir, so you want to resolve the vm if it's a symlink, and then go up one dir.

@radicaled @lukechurch

### PR DESCRIPTION
**Pull request by radicaled**
SdkService.discoverSdkPath tries to find the user's SDK path by
examining their PATH. This only works on Windows (theoretically) and
Atom instances that are launched from the shell (and thus inherit the
shell's PATH).

Closes #60

### CODE REVIEW

**Comment by radicaled** [comment]
@devoncarew 

Do you have a Windows box you can try this branch on to confirm it works on Windows?

**Comment by devoncarew** [comment]
I have one I can try this on tonight - happy to give it a shot.

Here's a link to some code that will let you locate the sdk on a mac, even if atom isn't launched from the shell: https://github.com/devoncarew/tools/blob/master/org.dartlang.tools/src/org/dartlang/tools/sdk/DartSdkManager.java#L51

**Comment by radicaled** [comment]
@devoncarew 

The problem here is either in Electron Shell or Yosemite: https://github.com/atom/electron/issues/550.

So the path is sanitized if Atom isn't launched from the shell, unfortunately.

**Comment by radicaled** [comment]
As for the code you linked to:

`String result = ProcessUtils.exec(new String[] {"/bin/bash", "-l", "-c", "which dart"});`

zsh is pretty popular these days, so I don't think this will work for a number of people (including me!).

**Comment by devoncarew** [comment]
Hmm, it look like my windows machine is in a pretty bad state. I can't run atom on it; I think I'll have to re-image the machine.

**Comment by radicaled** [comment]
Gonna merge this; if there's a Windows-specific issue that crops up, will do a bugfix release, but looking over the code again, there shouldn't be any problems.

**Pull request merged**
